# SPDX-FileCopyrightText: 2022 Great Software Laboratory Pvt. Ltd
# SPDX-FileCopyrightText: 2021 Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: Apache-2.0


---
info:
  version: 1.0.0
  description: GNBSIM initial local configuration

configuration:
  singleInterface: false #default value
  execInParallel: false #run all profiles in parallel
  httpServer: # Serves APIs to create/control profiles on the go
    enable: true
    ipAddr: "POD_IP"
    port: 8080
  gnbs: # pool of gNodeBs
    gnb1:
      n2IpAddr: 192.168.60.1 # gNB N2 interface IP address used to connect to AMF 
      n2Port: 9487 # gNB N2 Port used to connect to AMF
      n3IpAddr: 192.168.60.1 # gNB N3 interface IP address used to connect to UPF. when singleInterface mode is false
      #n3IpAddr: "POD_IP" # when gnb is deployed in singleInterface mode
      n3Port: 2152 # gNB N3 Port used to connect to UPF
      name: gnb1 # gNB name that uniquely identify a gNB within application
      globalRanId:
        plmnId:
          mcc: 001 # Mobile Country Code (3 digits string, digit: 0~9)
          mnc: 01 # Mobile Network Code (2 or 3 digits string, digit: 0~9)
        gNbId: 
          bitLength: 24
          gNBValue: 000102 # gNB identifier (3 bytes hex string, range: 000000~FFFFFF)
      supportedTaList:
        - tac: 000001 # Tracking Area Code (3 bytes hex string, range: 000000~FFFFFF)
          broadcastPlmnList:
            - plmnId:
                mcc: 001
                mnc: 01
              taiSliceSupportList:
                - sst: 1 # Slice/Service Type (uinteger, range: 0~255)
                  sd: FFFFFF # Slice Differentiator (3 bytes hex string, range: 000000~FFFFFF)
                - sst: 1
                  sd: FFFFFF
                - sst: 2
      defaultAmf:
        hostName: MAGMAAMF1 # Host name of AMF
        ipAddr: 192.168.60.142 # AMF IP address
        port: 38412 # AMF port

  customProfiles:
    customProfiles1:
      profileType: custom # profile type
      profileName: custom1 # uniqely identifies a profile within application
      enable: true # Set true to execute the profile, false otherwise.
      execInParallel: false #run all subscribers in parallel 
      stepTrigger: false #wait for trigger to move to next step
      gnbName: gnb1 # gNB to be used for this profile
      startImsi: 001010000000001
      ueCount: 1
      defaultAs: "192.168.60.1" #default icmp pkt destination
      opc: "E8ED289DEBA952E4283B54E88E6183CA"
      key: "465B5CE8B199B49FAA5F0A2EE238A6BC"
      sequenceNumber: "16f3b3f70fc2"
      plmnId: # Public Land Mobile Network ID, <PLMN ID> = <MCC><MNC>
        mcc: 001 # Mobile Country Code (3 digits string, digit: 0~9)
        mnc: 01 # Mobile Network Code (2 or 3 digits string, digit: 0~9)
      startiteration: iteration1
      iterations:
        #at max 7 actions
        - "name": "iteration1"
          "1": "REGISTRATION-PROCEDURE 5"
          "2": "PDU-SESSION-ESTABLISHMENT-PROCEDURE 5"
          "3": "UE-INITIATED-DEREGISTRATION-PROCEDURE 10"
          # "3": "USER-DATA-PACKET-GENERATION-PROCEDURE 10"
          #   "next":  "iteration2"
          # - "name": "iteration2"
          # "1": "AN-RELEASE-PROCEDURE 100"
          # "2": "UE-TRIGGERED-SERVICE-REQUEST-PROCEDURE 10"
          # "repeat": 5
          # "next":  "iteration3"
          # - "name": "iteration3"
          # "1": "UE-INITIATED-DEREGISTRATION-PROCEDURE 10"
          #"repeat": 0 #default value 0 . i.e execute once
          #"next":  "quit" #default value quit. i.e. no further iteration to run

  profiles: # profile information
    - profileType: register # profile type
      profileName: profile1 # uniqely identifies a profile within application
      enable: false # Set true to execute the profile, false otherwise.
      gnbName: gnb1 # gNB to be used for this profile
      startImsi: 001010000000001
      ueCount: 1
      defaultAs: "192.168.60.1" #default icmp pkt destination
      opc: "E8ED289DEBA952E4283B54E88E6183CA"
      key: "465B5CE8B199B49FAA5F0A2EE238A6BC"
      sequenceNumber: "16f3b3f70fc2"
      dnn: "internet"
      sNssai:
        sst: 1 # Slice/Service Type (uinteger, range: 0~255)
        sd: FFFFFF # Slice Differentiator (3 bytes hex string, range: 000000~FFFFFF)
      execInParallel: false #run all subscribers within profile in parallel
      plmnId: # Public Land Mobile Network ID, <PLMN ID> = <MCC><MNC>
        mcc: 001 # Mobile Country Code (3 digits string, digit: 0~9)
        mnc: 01 # Mobile Network Code (2 or 3 digits string, digit: 0~9)
    - profileType: pdusessest # profile type
      profileName: profile2 # uniqely identifies a profile within application
      enable: false # Set true to execute the profile, false otherwise.
      gnbName: gnb1 # gNB to be used for this profile
      startImsi: 001010000000001 # First IMSI. Subsequent values will be used if ueCount is more than 1
      ueCount: 1 # Number of UEs for for which the profile will be executed
      defaultAs: "192.168.60.1" #default icmp pkt destination
      opc: "E8ED289DEBA952E4283B54E88E6183CA"
      key: "465B5CE8B199B49FAA5F0A2EE238A6BC"
      sequenceNumber: "16f3b3f70fc2"
      dnn: "internet"
      sNssai:
        sst: 1 # Slice/Service Type (uinteger, range: 0~255)
        sd: FFFFFF # Slice Differentiator (3 bytes hex string, range: 000000~FFFFFF)
      execInParallel: false #run all subscribers within profile in parallel
      plmnId: # Public Land Mobile Network ID, <PLMN ID> = <MCC><MNC>. Should match startImsi
        mcc: 001 # Mobile Country Code (3 digits string, digit: 0~9)
        mnc: 01 # Mobile Network Code (2 or 3 digits string, digit: 0~9)
      dataPktCount: 5 # Number of UL user data packets to be transmitted. Common for all UEs
    - profileType: anrelease # profile type
      profileName: profile3 # uniqely identifies a profile within application
      enable: false # Set true to execute the profile, false otherwise.
      gnbName: gnb1 # gNB to be used for this profile
      startImsi: 001010000000001 # First IMSI. Subsequent values will be used if ueCount is more than 1
      ueCount: 5 # Number of UEs for for which the profile will be executed
      defaultAs: "192.168.250.1" #default icmp pkt destination
      opc: "E8ED289DEBA952E4283B54E88E6183CA"
      key: "465B5CE8B199B49FAA5F0A2EE238A6BC"
      sequenceNumber: "16f3b3f70fc2"
      dnn: "internet"
      sNssai:
        sst: 1 # Slice/Service Type (uinteger, range: 0~255)
        sd: FFFFFF # Slice Differentiator (3 bytes hex string, range: 000000~FFFFFF)
      execInParallel: false #run all subscribers within profile in parallel
      plmnId: # Public Land Mobile Network ID, <PLMN ID> = <MCC><MNC>. Should match startImsi
        mcc: 001 # Mobile Country Code (3 digits string, digit: 0~9)
        mnc: 01 # Mobile Network Code (2 or 3 digits string, digit: 0~9)
    - profileType: uetriggservicereq # profile type
      profileName: profile4 # uniqely identifies a profile within application
      enable: false # Set true to execute the profile, false otherwise.
      gnbName: gnb1 # gNB to be used for this profile
      startImsi: 001010000000001 # First IMSI. Subsequent values will be used if ueCount is more than 1
      ueCount: 5 # Number of UEs for for which the profile will be executed
      defaultAs: "192.168.250.1" #default icmp pkt destination
      opc: "E8ED289DEBA952E4283B54E88E6183CA"
      key: "465B5CE8B199B49FAA5F0A2EE238A6BC"
      sequenceNumber: "16f3b3f70fc2"
      dnn: "internet"
      sNssai:
        sst: 1 # Slice/Service Type (uinteger, range: 0~255)
        sd: FFFFFF # Slice Differentiator (3 bytes hex string, range: 000000~FFFFFF)
      execInParallel: false #run all subscribers within profile in parallel
      plmnId: # Public Land Mobile Network ID, <PLMN ID> = <MCC><MNC>. Should match startImsi
        mcc: 001 # Mobile Country Code (3 digits string, digit: 0~9)
        mnc: 01 # Mobile Network Code (2 or 3 digits string, digit: 0~9)  
    - profileType: deregister # profile type
      profileName: profile5 # uniqely identifies a profile within application
      enable: false # Set true to execute the profile, false otherwise.
      gnbName: gnb1 # gNB to be used for this profile
      startImsi: 001010000000001 # First IMSI. Subsequent values will be used if ueCount is more than 1
      ueCount: 5 # Number of UEs for for which the profile will be executed
      defaultAs: "192.168.250.1" #default icmp pkt destination
      opc: "E8ED289DEBA952E4283B54E88E6183CA"
      key: "465B5CE8B199B49FAA5F0A2EE238A6BC"
      sequenceNumber: "16f3b3f70fc2"
      dnn: "internet"
      sNssai:
        sst: 1 # Slice/Service Type (uinteger, range: 0~255)
        sd: FFFFFF # Slice Differentiator (3 bytes hex string, range: 000000~FFFFFF)
      execInParallel: false #run all subscribers within profile in parallel
      plmnId: # Public Land Mobile Network ID, <PLMN ID> = <MCC><MNC>. Should match startImsi
        mcc: 001 # Mobile Country Code (3 digits string, digit: 0~9)
        mnc: 01 # Mobile Network Code (2 or 3 digits string, digit: 0~9)
    - profileType: nwtriggeruedereg # profile type
      profileName: profile6 # uniqely identifies a profile within application
      enable: false # Set true to execute the profile, false otherwise.
      gnbName: gnb1 # gNB to be used for this profile
      startImsi: 001010000000001 # First IMSI. Subsequent values will be used if ueCount is more than 1
      ueCount: 1 # Number of UEs for for which the profile will be executed
      defaultAs: "192.168.250.1" #default icmp pkt destination
      perUserTimeout: 10 #if no expected event received in this time then treat it as failure
      opc: "E8ED289DEBA952E4283B54E88E6183CA"
      key: "465B5CE8B199B49FAA5F0A2EE238A6BC"
      sequenceNumber: "16f3b3f70fc2"
      dnn: "internet"
      sNssai:
        sst: 1 # Slice/Service Type (uinteger, range: 0~255)
        sd: FFFFFF # Slice Differentiator (3 bytes hex string, range: 000000~FFFFFF)
      execInParallel: false #run all subscribers within profile in parallel
      plmnId: # Public Land Mobile Network ID, <PLMN ID> = <MCC><MNC>. Should match startImsi
        mcc: 001 # Mobile Country Code (3 digits string, digit: 0~9)
        mnc: 01 # Mobile Network Code (2 or 3 digits string, digit: 0~9)
    - profileType: uereqpdusessrelease # profile type
      profileName: profile7 # uniqely identifies a profile within application
      enable: false # Set true to execute the profile, false otherwise.
      gnbName: gnb1 # gNB to be used for this profile
      startImsi: 001010000000001 # First IMSI. Subsequent values will be used if ueCount is more than 1
      ueCount: 5 # Number of UEs for for which the profile will be executed
      opc: "E8ED289DEBA952E4283B54E88E6183CA"
      key: "465B5CE8B199B49FAA5F0A2EE238A6BC"
      sequenceNumber: "16f3b3f70fc2"
      dnn: "internet"
      sNssai:
        sst: 1 # Slice/Service Type (uinteger, range: 0~255)
        sd: FFFFFF # Slice Differentiator (3 bytes hex string, range: 000000~FFFFFF)
      execInParallel: false #run all subscribers within profile in parallel
      defaultAs: "192.168.250.1" #default icmp pkt destination
      plmnId: # Public Land Mobile Network ID, <PLMN ID> = <MCC><MNC>. Should match startImsi
        mcc: 001 # Mobile Country Code (3 digits string, digit: 0~9)
        mnc: 01 # Mobile Network Code (2 or 3 digits string, digit: 0~9)
    - profileType: nwreqpdusessrelease # profile type
      profileName: profile8 # uniqely identifies a profile within application
      enable: false # Set true to execute the profile, false otherwise.
      gnbName: gnb1 # gNB to be used for this profile
      startImsi: 001010000000001 # First IMSI. Subsequent values will be used if ueCount is more than 1
      ueCount: 1 # Number of UEs for for which the profile will be executed
      opc: "E8ED289DEBA952E4283B54E88E6183CA"
      key: "465B5CE8B199B49FAA5F0A2EE238A6BC"
      sequenceNumber: "16f3b3f70fc2"
      dnn: "internet"
      sNssai:
        sst: 1 # Slice/Service Type (uinteger, range: 0~255)
        sd: FFFFFF # Slice Differentiator (3 bytes hex string, range: 000000~FFFFFF)
      execInParallel: false #run all subscribers within profile in parallel
      defaultAs: "192.168.250.1" #default icmp pkt destination
      plmnId: # Public Land Mobile Network ID, <PLMN ID> = <MCC><MNC>. Should match startImsi
        mcc: 001 # Mobile Country Code (3 digits string, digit: 0~9)
        mnc: 01 # Mobile Network Code (2 or 3 digits string, digit: 0~9)

logger:
  logLevel: info # how detailed the log will be, values: trace, debug, info, warn, error, fatal, panic